# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ccef799490c93bd5d19f2353d1bf325fbf309cb230395e1c4908961f395950e55d51c685ad26cf72e746f60f1d0edb50f2a3ba949f8cc9e7181d17cf7738eef

test:
  secret_key_base: 1c86a322534c156785f24a532a944afc047ada8bf778d643a7b843e1c3092ea6323b0de5e953ab090c9c4f3d49101fb286cc39749223792780e77c3b03adb275

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
